name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Kiruthika Anbazhagan is learning Github Actions"
      - name: Print goodbye
        run: echo "Kiruthika Anbazhagan successfully completed Github Actions Migration for all the AHW Repositories"
